{% set name = "idds-workflow" %}
{% set version = "0.10.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cbc36837cf5f09dc9fc66221476532434aaf5feb2d5e2acdf29b6d0537f6ce3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - idds-common =={{ version }}
    - python >=3.6

test:
  imports:
    - idds
    - idds.workflow

about:
  home: https://pypi.org/project/idds-workflow/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: intelligent Data Delivery Service(iDDS) Package
  doc_url: https://idds.readthedocs.io/en/latest/
  dev_url: https://github.com/HSF/iDDS

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
