{% set name = "idds-workflow" %}
{% set name_pypi = "idds_workflow" %}
{% set version = "2.1.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: a95bf20fc6c0af02759c5228fdb9cb2d07127a8d9634c766c5b5b05009ae6cb3


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - idds-common =={{ version }}
    - python >=3.6
    - stomp.py

test:
  imports:
    - idds
    - idds.workflow

about:
  home: https://pypi.org/project/idds-workflow/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: intelligent Data Delivery Service(iDDS) Package
  doc_url: https://idds.readthedocs.io/en/latest/
  dev_url: https://github.com/HSF/iDDS

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
