{% set name = "idds-workflow" %}
{% set name_pypi = "idds_workflow" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: 4adb24c4f99f3390d74e241e03e2e5dced66286cba9463709e286a5473366eb6


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - idds-common =={{ version }}
    - python >={{ python_min }}
    - stomp.py

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.workflow

about:
  home: https://pypi.org/project/idds-workflow/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: intelligent Data Delivery Service(iDDS) Package
  doc_url: https://idds.readthedocs.io/en/latest/
  dev_url: https://github.com/HSF/iDDS

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
